/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedCareRadarRouteImport } from './routes/_authenticated/care-radar'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedFirstTimersRouteImport } from './routes/_authenticated/first-timers'
import { Route as AuthenticatedFollowUpRouteImport } from './routes/_authenticated/follow-up'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedPrayerRequestsRouteImport } from './routes/_authenticated/prayer-requests'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareRadarRoute = AuthenticatedCareRadarRouteImport.update({
  id: '/care-radar',
  path: '/care-radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirstTimersRoute =
  AuthenticatedFirstTimersRouteImport.update({
    id: '/first-timers',
    path: '/first-timers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowUpRoute = AuthenticatedFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrayerRequestsRoute =
  AuthenticatedPrayerRequestsRouteImport.update({
    id: '/prayer-requests',
    path: '/prayer-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/care-radar': typeof AuthenticatedCareRadarRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/first-timers': typeof AuthenticatedFirstTimersRoute
  '/follow-up': typeof AuthenticatedFollowUpRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/prayer-requests': typeof AuthenticatedPrayerRequestsRoute
  '/reports': typeof AuthenticatedReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/care-radar': typeof AuthenticatedCareRadarRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/first-timers': typeof AuthenticatedFirstTimersRoute
  '/follow-up': typeof AuthenticatedFollowUpRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/prayer-requests': typeof AuthenticatedPrayerRequestsRoute
  '/reports': typeof AuthenticatedReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/care-radar': typeof AuthenticatedCareRadarRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/first-timers': typeof AuthenticatedFirstTimersRoute
  '/_authenticated/follow-up': typeof AuthenticatedFollowUpRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/prayer-requests': typeof AuthenticatedPrayerRequestsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/care-radar'
    | '/communication'
    | '/departments'
    | '/events'
    | '/feedback'
    | '/first-timers'
    | '/follow-up'
    | '/groups'
    | '/members'
    | '/prayer-requests'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/care-radar'
    | '/communication'
    | '/departments'
    | '/events'
    | '/feedback'
    | '/first-timers'
    | '/follow-up'
    | '/groups'
    | '/members'
    | '/prayer-requests'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/care-radar'
    | '/_authenticated/communication'
    | '/_authenticated/departments'
    | '/_authenticated/events'
    | '/_authenticated/feedback'
    | '/_authenticated/first-timers'
    | '/_authenticated/follow-up'
    | '/_authenticated/groups'
    | '/_authenticated/members'
    | '/_authenticated/prayer-requests'
    | '/_authenticated/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/care-radar': {
      id: '/_authenticated/care-radar'
      path: '/care-radar'
      fullPath: '/care-radar'
      preLoaderRoute: typeof AuthenticatedCareRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/first-timers': {
      id: '/_authenticated/first-timers'
      path: '/first-timers'
      fullPath: '/first-timers'
      preLoaderRoute: typeof AuthenticatedFirstTimersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-up': {
      id: '/_authenticated/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof AuthenticatedFollowUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayer-requests': {
      id: '/_authenticated/prayer-requests'
      path: '/prayer-requests'
      fullPath: '/prayer-requests'
      preLoaderRoute: typeof AuthenticatedPrayerRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedCareRadarRoute: typeof AuthenticatedCareRadarRoute
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedFirstTimersRoute: typeof AuthenticatedFirstTimersRoute
  AuthenticatedFollowUpRoute: typeof AuthenticatedFollowUpRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedPrayerRequestsRoute: typeof AuthenticatedPrayerRequestsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedCareRadarRoute: AuthenticatedCareRadarRoute,
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedFirstTimersRoute: AuthenticatedFirstTimersRoute,
  AuthenticatedFollowUpRoute: AuthenticatedFollowUpRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedPrayerRequestsRoute: AuthenticatedPrayerRequestsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
