/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedCareRadarRouteImport } from './routes/_authenticated/care-radar'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedFirstTimersRouteImport } from './routes/_authenticated/first-timers'
import { Route as AuthenticatedFollowUpRouteImport } from './routes/_authenticated/follow-up'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPrayerRequestsRouteImport } from './routes/_authenticated/prayer-requests'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance.index'
import { Route as AuthenticatedFirstTimersIndexRouteImport } from './routes/_authenticated/first-timers.index'
import { Route as AuthenticatedFirstTimersFirstTimerIdRouteImport } from './routes/_authenticated/first-timers.$firstTimerId'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedMembersMemberIdRouteImport } from './routes/_authenticated/members.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareRadarRoute = AuthenticatedCareRadarRouteImport.update({
  id: '/care-radar',
  path: '/care-radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirstTimersRoute =
  AuthenticatedFirstTimersRouteImport.update({
    id: '/first-timers',
    path: '/first-timers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowUpRoute = AuthenticatedFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrayerRequestsRoute =
  AuthenticatedPrayerRequestsRouteImport.update({
    id: '/prayer-requests',
    path: '/prayer-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedFirstTimersIndexRoute =
  AuthenticatedFirstTimersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFirstTimersRoute,
  } as any)
const AuthenticatedFirstTimersFirstTimerIdRoute =
  AuthenticatedFirstTimersFirstTimerIdRouteImport.update({
    id: '/$firstTimerId',
    path: '/$firstTimerId',
    getParentRoute: () => AuthenticatedFirstTimersRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedMembersMemberIdRoute =
  AuthenticatedMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/care-radar': typeof AuthenticatedCareRadarRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/first-timers': typeof AuthenticatedFirstTimersRouteWithChildren
  '/follow-up': typeof AuthenticatedFollowUpRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prayer-requests': typeof AuthenticatedPrayerRequestsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/first-timers/$firstTimerId': typeof AuthenticatedFirstTimersFirstTimerIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/first-timers/': typeof AuthenticatedFirstTimersIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/care-radar': typeof AuthenticatedCareRadarRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/follow-up': typeof AuthenticatedFollowUpRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prayer-requests': typeof AuthenticatedPrayerRequestsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/first-timers/$firstTimerId': typeof AuthenticatedFirstTimersFirstTimerIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/first-timers': typeof AuthenticatedFirstTimersIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/_authenticated/care-radar': typeof AuthenticatedCareRadarRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/first-timers': typeof AuthenticatedFirstTimersRouteWithChildren
  '/_authenticated/follow-up': typeof AuthenticatedFollowUpRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/prayer-requests': typeof AuthenticatedPrayerRequestsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/first-timers/$firstTimerId': typeof AuthenticatedFirstTimersFirstTimerIdRoute
  '/_authenticated/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/first-timers/': typeof AuthenticatedFirstTimersIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/attendance'
    | '/care-radar'
    | '/communication'
    | '/dashboard'
    | '/departments'
    | '/events'
    | '/feedback'
    | '/first-timers'
    | '/follow-up'
    | '/groups'
    | '/members'
    | '/onboarding'
    | '/prayer-requests'
    | '/reports'
    | '/settings'
    | '/first-timers/$firstTimerId'
    | '/members/$memberId'
    | '/attendance/'
    | '/first-timers/'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/care-radar'
    | '/communication'
    | '/dashboard'
    | '/departments'
    | '/events'
    | '/feedback'
    | '/follow-up'
    | '/groups'
    | '/onboarding'
    | '/prayer-requests'
    | '/reports'
    | '/settings'
    | '/first-timers/$firstTimerId'
    | '/members/$memberId'
    | '/attendance'
    | '/first-timers'
    | '/members'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/attendance'
    | '/_authenticated/care-radar'
    | '/_authenticated/communication'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/events'
    | '/_authenticated/feedback'
    | '/_authenticated/first-timers'
    | '/_authenticated/follow-up'
    | '/_authenticated/groups'
    | '/_authenticated/members'
    | '/_authenticated/onboarding'
    | '/_authenticated/prayer-requests'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/first-timers/$firstTimerId'
    | '/_authenticated/members/$memberId'
    | '/_authenticated/attendance/'
    | '/_authenticated/first-timers/'
    | '/_authenticated/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/care-radar': {
      id: '/_authenticated/care-radar'
      path: '/care-radar'
      fullPath: '/care-radar'
      preLoaderRoute: typeof AuthenticatedCareRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/first-timers': {
      id: '/_authenticated/first-timers'
      path: '/first-timers'
      fullPath: '/first-timers'
      preLoaderRoute: typeof AuthenticatedFirstTimersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-up': {
      id: '/_authenticated/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof AuthenticatedFollowUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayer-requests': {
      id: '/_authenticated/prayer-requests'
      path: '/prayer-requests'
      fullPath: '/prayer-requests'
      preLoaderRoute: typeof AuthenticatedPrayerRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/first-timers/': {
      id: '/_authenticated/first-timers/'
      path: '/'
      fullPath: '/first-timers/'
      preLoaderRoute: typeof AuthenticatedFirstTimersIndexRouteImport
      parentRoute: typeof AuthenticatedFirstTimersRoute
    }
    '/_authenticated/first-timers/$firstTimerId': {
      id: '/_authenticated/first-timers/$firstTimerId'
      path: '/$firstTimerId'
      fullPath: '/first-timers/$firstTimerId'
      preLoaderRoute: typeof AuthenticatedFirstTimersFirstTimerIdRouteImport
      parentRoute: typeof AuthenticatedFirstTimersRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/members/$memberId': {
      id: '/_authenticated/members/$memberId'
      path: '/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
  }
}

interface AuthenticatedAttendanceRouteChildren {
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
}

const AuthenticatedAttendanceRouteChildren: AuthenticatedAttendanceRouteChildren =
  {
    AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  }

const AuthenticatedAttendanceRouteWithChildren =
  AuthenticatedAttendanceRoute._addFileChildren(
    AuthenticatedAttendanceRouteChildren,
  )

interface AuthenticatedFirstTimersRouteChildren {
  AuthenticatedFirstTimersFirstTimerIdRoute: typeof AuthenticatedFirstTimersFirstTimerIdRoute
  AuthenticatedFirstTimersIndexRoute: typeof AuthenticatedFirstTimersIndexRoute
}

const AuthenticatedFirstTimersRouteChildren: AuthenticatedFirstTimersRouteChildren =
  {
    AuthenticatedFirstTimersFirstTimerIdRoute:
      AuthenticatedFirstTimersFirstTimerIdRoute,
    AuthenticatedFirstTimersIndexRoute: AuthenticatedFirstTimersIndexRoute,
  }

const AuthenticatedFirstTimersRouteWithChildren =
  AuthenticatedFirstTimersRoute._addFileChildren(
    AuthenticatedFirstTimersRouteChildren,
  )

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersMemberIdRoute: typeof AuthenticatedMembersMemberIdRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersMemberIdRoute: AuthenticatedMembersMemberIdRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRouteWithChildren
  AuthenticatedCareRadarRoute: typeof AuthenticatedCareRadarRoute
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedFirstTimersRoute: typeof AuthenticatedFirstTimersRouteWithChildren
  AuthenticatedFollowUpRoute: typeof AuthenticatedFollowUpRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPrayerRequestsRoute: typeof AuthenticatedPrayerRequestsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRouteWithChildren,
  AuthenticatedCareRadarRoute: AuthenticatedCareRadarRoute,
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedFirstTimersRoute: AuthenticatedFirstTimersRouteWithChildren,
  AuthenticatedFollowUpRoute: AuthenticatedFollowUpRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPrayerRequestsRoute: AuthenticatedPrayerRequestsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
